### ISSUE TITLE
translatable strings

### ISSUE THREAD

**Issue by kixe** [thetuningspoon/AdminPageFieldEditLinks#1]
Module doesn't appear in the list of translatable files, because it isn't detected as translatable. Call translator from the module object itself with '$this->_(' instead of  '$event->object->_('

**Comment by thetuningspoon** [comment]
Thanks. At this point I haven't made any effort to make the module translatable, but I will now that you've pointed this out.

**Comment by thetuningspoon** [comment]
Still trying to figure out how to work this issue tracker and add new labels. Anyway, this is fixed in the latest commit. Thanks!

**Comment by kixe** [comment]
String " View " should be replaced 2 more times in js. Thanks for the enhancement.

**Comment by thetuningspoon** [comment]
Sorry, I missed that! This is now fixed. Also, I noticed that I somehow flubbed the commit of the main .module file last night and the version number was not updated. Both of these issues are now fixed in 3.0.1. Let me know if you run into any other bugs or have any suggestions for additional enhancements.
